// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Brokerage.proto

package protobuf;

public final class brokerageProtocol {
  private brokerageProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface creatorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authenticator.creator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 kWh = 1;</code>
     */
    boolean hasKWh();
    /**
     * <code>optional int32 kWh = 1;</code>
     */
    int getKWh();

    /**
     * <code>optional .authenticator.creator.Type type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>optional .authenticator.creator.Type type = 2;</code>
     */
    protobuf.brokerageProtocol.creator.Type getType();
  }
  /**
   * Protobuf type {@code authenticator.creator}
   */
  public static final class creator extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:authenticator.creator)
      creatorOrBuilder {
    // Use creator.newBuilder() to construct.
    private creator(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private creator(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final creator defaultInstance;
    public static creator getDefaultInstance() {
      return defaultInstance;
    }

    public creator getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private creator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              kWh_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              protobuf.brokerageProtocol.creator.Type value = protobuf.brokerageProtocol.creator.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.brokerageProtocol.internal_static_authenticator_creator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.brokerageProtocol.internal_static_authenticator_creator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.brokerageProtocol.creator.class, protobuf.brokerageProtocol.creator.Builder.class);
    }

    public static com.google.protobuf.Parser<creator> PARSER =
        new com.google.protobuf.AbstractParser<creator>() {
      public creator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new creator(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<creator> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code authenticator.creator.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ATOM = 0;</code>
       */
      ATOM(0, 0),
      /**
       * <code>KOHLE = 1;</code>
       */
      KOHLE(1, 1),
      /**
       * <code>OEL = 2;</code>
       */
      OEL(2, 2),
      /**
       * <code>GAS = 3;</code>
       */
      GAS(3, 3),
      /**
       * <code>OEKO = 4;</code>
       */
      OEKO(4, 4),
      ;

      /**
       * <code>ATOM = 0;</code>
       */
      public static final int ATOM_VALUE = 0;
      /**
       * <code>KOHLE = 1;</code>
       */
      public static final int KOHLE_VALUE = 1;
      /**
       * <code>OEL = 2;</code>
       */
      public static final int OEL_VALUE = 2;
      /**
       * <code>GAS = 3;</code>
       */
      public static final int GAS_VALUE = 3;
      /**
       * <code>OEKO = 4;</code>
       */
      public static final int OEKO_VALUE = 4;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return ATOM;
          case 1: return KOHLE;
          case 2: return OEL;
          case 3: return GAS;
          case 4: return OEKO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.brokerageProtocol.creator.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:authenticator.creator.Type)
    }

    private int bitField0_;
    public static final int KWH_FIELD_NUMBER = 1;
    private int kWh_;
    /**
     * <code>optional int32 kWh = 1;</code>
     */
    public boolean hasKWh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 kWh = 1;</code>
     */
    public int getKWh() {
      return kWh_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private protobuf.brokerageProtocol.creator.Type type_;
    /**
     * <code>optional .authenticator.creator.Type type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .authenticator.creator.Type type = 2;</code>
     */
    public protobuf.brokerageProtocol.creator.Type getType() {
      return type_;
    }

    private void initFields() {
      kWh_ = 0;
      type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, kWh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, kWh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.brokerageProtocol.creator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.creator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.brokerageProtocol.creator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.brokerageProtocol.creator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.brokerageProtocol.creator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authenticator.creator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authenticator.creator)
        protobuf.brokerageProtocol.creatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.brokerageProtocol.internal_static_authenticator_creator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.brokerageProtocol.internal_static_authenticator_creator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.brokerageProtocol.creator.class, protobuf.brokerageProtocol.creator.Builder.class);
      }

      // Construct using protobuf.brokerageProtocol.creator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        kWh_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.brokerageProtocol.internal_static_authenticator_creator_descriptor;
      }

      public protobuf.brokerageProtocol.creator getDefaultInstanceForType() {
        return protobuf.brokerageProtocol.creator.getDefaultInstance();
      }

      public protobuf.brokerageProtocol.creator build() {
        protobuf.brokerageProtocol.creator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.brokerageProtocol.creator buildPartial() {
        protobuf.brokerageProtocol.creator result = new protobuf.brokerageProtocol.creator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.kWh_ = kWh_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.brokerageProtocol.creator) {
          return mergeFrom((protobuf.brokerageProtocol.creator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.brokerageProtocol.creator other) {
        if (other == protobuf.brokerageProtocol.creator.getDefaultInstance()) return this;
        if (other.hasKWh()) {
          setKWh(other.getKWh());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.brokerageProtocol.creator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.brokerageProtocol.creator) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int kWh_ ;
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public boolean hasKWh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public int getKWh() {
        return kWh_;
      }
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public Builder setKWh(int value) {
        bitField0_ |= 0x00000001;
        kWh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public Builder clearKWh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        kWh_ = 0;
        onChanged();
        return this;
      }

      private protobuf.brokerageProtocol.creator.Type type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
      /**
       * <code>optional .authenticator.creator.Type type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .authenticator.creator.Type type = 2;</code>
       */
      public protobuf.brokerageProtocol.creator.Type getType() {
        return type_;
      }
      /**
       * <code>optional .authenticator.creator.Type type = 2;</code>
       */
      public Builder setType(protobuf.brokerageProtocol.creator.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .authenticator.creator.Type type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:authenticator.creator)
    }

    static {
      defaultInstance = new creator(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:authenticator.creator)
  }

  public interface consumerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authenticator.consumer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 kWh = 1;</code>
     */
    boolean hasKWh();
    /**
     * <code>optional int32 kWh = 1;</code>
     */
    int getKWh();

    /**
     * <code>optional int32 price = 2;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional int32 price = 2;</code>
     */
    int getPrice();

    /**
     * <code>optional .authenticator.creator.Type type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional .authenticator.creator.Type type = 3;</code>
     */
    protobuf.brokerageProtocol.creator.Type getType();

    /**
     * <code>optional int32 anzTage = 4;</code>
     *
     * <pre>
     *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
     * </pre>
     */
    boolean hasAnzTage();
    /**
     * <code>optional int32 anzTage = 4;</code>
     *
     * <pre>
     *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
     * </pre>
     */
    int getAnzTage();
  }
  /**
   * Protobuf type {@code authenticator.consumer}
   */
  public static final class consumer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:authenticator.consumer)
      consumerOrBuilder {
    // Use consumer.newBuilder() to construct.
    private consumer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private consumer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final consumer defaultInstance;
    public static consumer getDefaultInstance() {
      return defaultInstance;
    }

    public consumer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private consumer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              kWh_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              price_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              protobuf.brokerageProtocol.creator.Type value = protobuf.brokerageProtocol.creator.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              anzTage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.brokerageProtocol.internal_static_authenticator_consumer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.brokerageProtocol.internal_static_authenticator_consumer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.brokerageProtocol.consumer.class, protobuf.brokerageProtocol.consumer.Builder.class);
    }

    public static com.google.protobuf.Parser<consumer> PARSER =
        new com.google.protobuf.AbstractParser<consumer>() {
      public consumer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new consumer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<consumer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KWH_FIELD_NUMBER = 1;
    private int kWh_;
    /**
     * <code>optional int32 kWh = 1;</code>
     */
    public boolean hasKWh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 kWh = 1;</code>
     */
    public int getKWh() {
      return kWh_;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;
    /**
     * <code>optional int32 price = 2;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 price = 2;</code>
     */
    public int getPrice() {
      return price_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private protobuf.brokerageProtocol.creator.Type type_;
    /**
     * <code>optional .authenticator.creator.Type type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .authenticator.creator.Type type = 3;</code>
     */
    public protobuf.brokerageProtocol.creator.Type getType() {
      return type_;
    }

    public static final int ANZTAGE_FIELD_NUMBER = 4;
    private int anzTage_;
    /**
     * <code>optional int32 anzTage = 4;</code>
     *
     * <pre>
     *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
     * </pre>
     */
    public boolean hasAnzTage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 anzTage = 4;</code>
     *
     * <pre>
     *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
     * </pre>
     */
    public int getAnzTage() {
      return anzTage_;
    }

    private void initFields() {
      kWh_ = 0;
      price_ = 0;
      type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
      anzTage_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, kWh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, anzTage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, kWh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, anzTage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.brokerageProtocol.consumer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.consumer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.brokerageProtocol.consumer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.brokerageProtocol.consumer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.brokerageProtocol.consumer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authenticator.consumer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authenticator.consumer)
        protobuf.brokerageProtocol.consumerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.brokerageProtocol.internal_static_authenticator_consumer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.brokerageProtocol.internal_static_authenticator_consumer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.brokerageProtocol.consumer.class, protobuf.brokerageProtocol.consumer.Builder.class);
      }

      // Construct using protobuf.brokerageProtocol.consumer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        kWh_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
        bitField0_ = (bitField0_ & ~0x00000004);
        anzTage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.brokerageProtocol.internal_static_authenticator_consumer_descriptor;
      }

      public protobuf.brokerageProtocol.consumer getDefaultInstanceForType() {
        return protobuf.brokerageProtocol.consumer.getDefaultInstance();
      }

      public protobuf.brokerageProtocol.consumer build() {
        protobuf.brokerageProtocol.consumer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.brokerageProtocol.consumer buildPartial() {
        protobuf.brokerageProtocol.consumer result = new protobuf.brokerageProtocol.consumer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.kWh_ = kWh_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.anzTage_ = anzTage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.brokerageProtocol.consumer) {
          return mergeFrom((protobuf.brokerageProtocol.consumer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.brokerageProtocol.consumer other) {
        if (other == protobuf.brokerageProtocol.consumer.getDefaultInstance()) return this;
        if (other.hasKWh()) {
          setKWh(other.getKWh());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAnzTage()) {
          setAnzTage(other.getAnzTage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.brokerageProtocol.consumer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.brokerageProtocol.consumer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int kWh_ ;
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public boolean hasKWh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public int getKWh() {
        return kWh_;
      }
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public Builder setKWh(int value) {
        bitField0_ |= 0x00000001;
        kWh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 kWh = 1;</code>
       */
      public Builder clearKWh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        kWh_ = 0;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <code>optional int32 price = 2;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 price = 2;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>optional int32 price = 2;</code>
       */
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 price = 2;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0;
        onChanged();
        return this;
      }

      private protobuf.brokerageProtocol.creator.Type type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
      /**
       * <code>optional .authenticator.creator.Type type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .authenticator.creator.Type type = 3;</code>
       */
      public protobuf.brokerageProtocol.creator.Type getType() {
        return type_;
      }
      /**
       * <code>optional .authenticator.creator.Type type = 3;</code>
       */
      public Builder setType(protobuf.brokerageProtocol.creator.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .authenticator.creator.Type type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = protobuf.brokerageProtocol.creator.Type.ATOM;
        onChanged();
        return this;
      }

      private int anzTage_ ;
      /**
       * <code>optional int32 anzTage = 4;</code>
       *
       * <pre>
       *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
       * </pre>
       */
      public boolean hasAnzTage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 anzTage = 4;</code>
       *
       * <pre>
       *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
       * </pre>
       */
      public int getAnzTage() {
        return anzTage_;
      }
      /**
       * <code>optional int32 anzTage = 4;</code>
       *
       * <pre>
       *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
       * </pre>
       */
      public Builder setAnzTage(int value) {
        bitField0_ |= 0x00000008;
        anzTage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 anzTage = 4;</code>
       *
       * <pre>
       *für wie viele tage weil es einige verbraucher gibt, die für die nächsten 6 jahre strom kaufen
       * </pre>
       */
      public Builder clearAnzTage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        anzTage_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:authenticator.consumer)
    }

    static {
      defaultInstance = new consumer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:authenticator.consumer)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticator_creator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_authenticator_creator_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticator_consumer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_authenticator_consumer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Brokerage.proto\022\rauthenticator\"z\n\007crea" +
      "tor\022\013\n\003kWh\030\001 \001(\005\022)\n\004type\030\002 \001(\0162\033.authent" +
      "icator.creator.Type\"7\n\004Type\022\010\n\004ATOM\020\000\022\t\n" +
      "\005KOHLE\020\001\022\007\n\003OEL\020\002\022\007\n\003GAS\020\003\022\010\n\004OEKO\020\004\"b\n\010" +
      "consumer\022\013\n\003kWh\030\001 \001(\005\022\r\n\005price\030\002 \001(\005\022)\n\004" +
      "type\030\003 \001(\0162\033.authenticator.creator.Type\022" +
      "\017\n\007anzTage\030\004 \001(\005B\035\n\010protobufB\021brokerageP" +
      "rotocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authenticator_creator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authenticator_creator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_authenticator_creator_descriptor,
        new java.lang.String[] { "KWh", "Type", });
    internal_static_authenticator_consumer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authenticator_consumer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_authenticator_consumer_descriptor,
        new java.lang.String[] { "KWh", "Price", "Type", "AnzTage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
